when:
  - event: [push, pull_request]

steps:
  - name: CI
    image: ubuntu-latest
    commands:
      # Install bun
      - npm install -g bun && bun install

      # Copy .env file
      - find . -type f -name ".env.example" -exec sh -c 'cp "$1" "$${1%.*}"' _ {} \;

      # Check typescript types
      - bun run typecheck

      # Lint & check formatting
      - bun run check

