when:
  - event: push
    branch: main

steps:
  - name: Build
    image: node:22-alpine
    commands:
      - npm install -g bun && bun install
      - printf "RESEND_API_KEY=${RESEND_API_KEY}\nRESEND_FROM_ADDRESS=${RESEND_FROM_ADDRESS\nRESEND_TO_ADDRESS=${RESEND_TO_ADDRESS}" > .env
      - bun run build
      - bun run vercel deploy

