# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

when:
  - event: [push, pull_request, manual]

steps:
  - name: Deploy preview
    image: node:22-alpine
    when:
      - event: [manual, pull_request]
        branch:
          exclude: main
    environment:
      VERCEL_ORG_ID: ${VERCEL_ORG_ID}
      VERCEL_PROJECT_ID: ${VERCEL_PROJECT_ID}
    commands:
      # Install bun
      - npm install -g bun && bun install

      # Add env variables to .env
      - printf "RESEND_API_KEY=${RESEND_API_KEY}\nRESEND_FROM_ADDRESS=${RESEND_FROM_ADDRESS}\nRESEND_TO_ADDRESS=${RESEND_TO_ADDRESS}" > .env

      # Build project
      - bun run build

      # Deploy on vercel
      - bun run vercel deploy --prebuilt --token=${VERCEL_TOKEN}

  - name: Deploy prod
    image: node:22-alpine
    when:
      - branch: main
    environment:
      VERCEL_ORG_ID: ${VERCEL_ORG_ID}
      VERCEL_PROJECT_ID: ${VERCEL_PROJECT_ID}
    commands:
      # Install bun
      - npm install -g bun && bun install

      # Add env variables to .env
      - printf "RESEND_API_KEY=${RESEND_API_KEY}\nRESEND_FROM_ADDRESS=${RESEND_FROM_ADDRESS}\nRESEND_TO_ADDRESS=${RESEND_TO_ADDRESS}" > .env

      # Build project
      - bun run build

      # Deploy on vercel
      - bun run vercel deploy --prebuilt --prod --token=${VERCEL_TOKEN}
