when:
  - event: push

steps:
  - name: CI
    image: node:22-alpine
    commands:
      # Install bun
      - npm install -g bun && bun install

      # Copy .env file
      - find . -type f -name ".env.example" -exec sh -c 'cp "$1" "$${1%.*}"' _ {} \;
      - str=$(cat .env); printf "$${str//=/=dummy_value}" > .env

      # Check typescript types
      - bun run typecheck

      # Lint & check formatting
      - bun run check

      # Build project
      - bun run build
