# yaml-language-server: $schema=https://raw.githubusercontent.com/woodpecker-ci/woodpecker/main/pipeline/frontend/yaml/linter/schema/schema.json

when:
  - event: push

steps:
  - name: CI
    image: node:22-alpine
    environment:
      SKIP_ENV_VALIDATION: true
    commands:
      # Install bun
      - npm install -g bun && bun install

      # Copy .env file
      - find . -type f -name ".env.example" -exec sh -c 'cp "$1" "$${1%.*}"' _ {} \;

      # Check typescript types
      - bun run typecheck

      # Lint & check formatting
      - bun run check

      # Build project
      - bun run build
